/**
 * Space Codex Data — Comprehensive Aerospace, Astrophysics & Planetary Defense Lexicon.
 * 
 * 100% English Terminology adhering strictly to IAU (International Astronomical Union)
 * and NASA JPL Standards.
 */

export type CodexCategory =
  | "astrophysics"
  | "planetary-defense"
  | "astrometry"
  | "orbital-mechanics"
  | "stellar-physics"
  | "planetary-science";

export interface CodexCategoryMeta {
  id: CodexCategory;
  name: string;
  shortDesc: string;
  icon: string; // Lucide icon identifier
  colorHex: string;
}

export interface CodexEntry {
  id: string;
  slug: string;
  term: string;
  category: CodexCategory;
  pronunciation?: string;
  iauStandardNotation?: string;
  shortDefinition: string;
  fullExplanation: string;
  formula?: {
    latex: string;
    explanation: string;
  };
  realWorldExample: string;
  astronomicalRelevance: string;
  difficulty: "Fundamental" | "Intermediate" | "Advanced";
  tags: string[];
  relatedTermIds: string[];
}

export const CODEX_CATEGORIES: Record<CodexCategory, CodexCategoryMeta> = {
  "astrophysics": {
    id: "astrophysics",
    name: "Astrophysics & Dynamics",
    shortDesc: "Celestial mechanics, gravitational physics, and fundamental cosmological constants.",
    icon: "Atom",
    colorHex: "#38bdf8", // Sky blue
  },
  "planetary-defense": {
    id: "planetary-defense",
    name: "Planetary Defense & NEOs",
    shortDesc: "Impact hazard scales, asteroid characterization, and kinetic deflection strategies.",
    icon: "ShieldAlert",
    colorHex: "#f87171", // Red
  },
  "astrometry": {
    id: "astrometry",
    name: "Astrometry & Observation",
    shortDesc: "Celestial coordinate systems, stellar magnitudes, ephemerides, and time standards.",
    icon: "Compass",
    colorHex: "#34d399", // Emerald
  },
  "orbital-mechanics": {
    id: "orbital-mechanics",
    name: "Spaceflight & Orbits",
    shortDesc: "Keplerian trajectories, delta-v budgets, orbital transfers, and propagation models.",
    icon: "Orbit",
    colorHex: "#a78bfa", // Purple
  },
  "stellar-physics": {
    id: "stellar-physics",
    name: "Stellar Physics & Deep Space",
    shortDesc: "Stellar lifecycles, degenerate matter, black holes, and high-energy phenomena.",
    icon: "Sparkles",
    colorHex: "#fbbf24", // Amber
  },
  "planetary-science": {
    id: "planetary-science",
    name: "Planetary Science & Habitability",
    shortDesc: "Atmospheric structures, magnetospheres, exoplanet geology, and biosignatures.",
    icon: "Globe",
    colorHex: "#22d3ee", // Cyan
  },
};

export const CODEX_ENTRIES: CodexEntry[] = [
  // ── 1. ASTROPHYSICS & CELESTIAL MECHANICS ───────────────────────────────────
  {
    id: "astronomical-unit",
    slug: "astronomical-unit",
    term: "Astronomical Unit (AU)",
    category: "astrophysics",
    iauStandardNotation: "au or AU",
    pronunciation: "/ˌæstrəˈnɒmɪkəl ˈjuːnɪt/",
    shortDefinition: "A standardized astronomical unit of length defined by the IAU as exactly 149,597,870,700 meters, representing the mean Earth-Sun distance.",
    fullExplanation: "The Astronomical Unit (AU) serves as the primary measuring tape for interplanetary distances within our Solar System and in exoplanetary architectures. Before 2012, the AU was derived dynamically from the Gaussian gravitational constant. In August 2012, the International Astronomical Union (IAU) Resolution B2 standardized the unit to an exact constant value of 149,597,870.7 km, decoupled from variations in Earth's elliptical orbit.",
    formula: {
      latex: "1\\text{ AU} = 1.495978707 \\times 10^{11}\\text{ m} \\approx 499.00478\\text{ light-seconds}",
      explanation: "Equivalent to roughly 8.317 light-minutes or approximately 215 Solar radii.",
    },
    realWorldExample: "Mercury is located at ~0.39 AU from the Sun, Mars at ~1.52 AU, Jupiter at ~5.20 AU, and Neptune at ~30.05 AU. Voyager 1 is currently over 160 AU from the Sun.",
    astronomicalRelevance: "Essential baseline for calculating stellar parallax, Keplerian orbital periods, and interplanetary spacecraft transfer trajectories.",
    difficulty: "Fundamental",
    tags: ["Constants", "Solar System", "Distance", "IAU Standard"],
    relatedTermIds: ["parsec", "light-year", "perihelion-aphelion", "keplers-laws"],
  },
  {
    id: "parsec",
    slug: "parsec",
    term: "Parsec (pc)",
    category: "astrophysics",
    iauStandardNotation: "pc",
    pronunciation: "/ˈpɑːrsɛk/",
    shortDefinition: "A unit of astronomical distance equal to the distance at which 1 Astronomical Unit subtends an angle of one arcsecond (~3.26 light-years).",
    fullExplanation: "The term 'parsec' is a portmanteau of 'parallax of one second'. It is the foundational geometric distance unit used by professional astrophysicists and astrometric observatories such as ESA Gaia and Hipparcos. When a star exhibits an annual trigonometric parallax angle of p = 1 arcsecond against distant background stars as Earth orbits the Sun, its distance is precisely 1 parsec.",
    formula: {
      latex: "d = \\frac{1}{p} \\quad \\text{where } 1\\text{ pc} = \\frac{1\\text{ AU}}{\\tan(1'')} \\approx 3.085677581 \\times 10^{16}\\text{ m} \\approx 3.26156\\text{ ly}",
      explanation: "Distance d in parsecs equals the reciprocal of the parallax angle p measured in arcseconds.",
    },
    realWorldExample: "Proxima Centauri, the nearest star to our Sun, is 1.30 pc (4.24 ly) away. The center of the Milky Way galaxy (Sagittarius A*) lies approximately 8,178 pc (8.18 kpc) from Earth.",
    astronomicalRelevance: "Universal standard for cosmic distance ladder calibrations, galactic dynamics (kpc), and extragalactic cosmography (Mpc/Gpc).",
    difficulty: "Intermediate",
    tags: ["Distance", "Trigonometric Parallax", "Cosmology", "Gaia"],
    relatedTermIds: ["astronomical-unit", "light-year", "apparent-absolute-magnitude", "redshift"],
  },
  {
    id: "light-year",
    slug: "light-year",
    term: "Light-Year (ly)",
    category: "astrophysics",
    iauStandardNotation: "ly",
    pronunciation: "/ˈlaɪt jɪər/",
    shortDefinition: "The distance that a photon of light travels in an absolute vacuum in one Julian year (365.25 days), equal to 9.46 trillion kilometers.",
    fullExplanation: "Although frequently mistaken in popular culture as a unit of time, the light-year is strictly a unit of length. Because photons travel at the universal cosmic speed limit c (299,792,458 m/s), measuring distances in light-years inherently reveals the lookback time of observed celestial phenomena. When observing a nebula located 1,000 light-years away, we witness its photons emitted 1,000 years in the past.",
    formula: {
      latex: "1\\text{ ly} = c \\times 1\\text{ Julian Year} = 299,792,458\\text{ m/s} \\times 31,557,600\\text{ s} = 9.460730472 \\times 10^{15}\\text{ m}",
      explanation: "Equivalent to approximately 63,241 AU or 0.3066 parsecs.",
    },
    realWorldExample: "The Andromeda Galaxy (M31) is 2.5 million light-years away, meaning the light reaching our telescopes today departed before modern humans walked the Earth.",
    astronomicalRelevance: "Intuitive metric for educational outreach, deep-sky astrophotography, and expressing cosmic lookback horizons.",
    difficulty: "Fundamental",
    tags: ["Speed of Light", "Distance", "Lookback Time", "Cosmology"],
    relatedTermIds: ["astronomical-unit", "parsec", "redshift"],
  },
  {
    id: "perihelion-aphelion",
    slug: "perihelion-aphelion",
    term: "Perihelion & Aphelion (Apsides)",
    category: "astrophysics",
    iauStandardNotation: "q (perihelion), Q (aphelion)",
    shortDefinition: "The points in the elliptical orbit of a celestial body where it is closest to (perihelion) and farthest from (aphelion) the Sun.",
    fullExplanation: "According to Kepler's First Law of Planetary Motion, all planetary orbits are ellipses with the Sun positioned at one focal point. The line connecting the perihelion and aphelion is termed the line of apsides (major axis of the ellipse). Because orbital velocity varies inversely with distance (Kepler's Second Law), bodies travel at their maximum orbital speed at perihelion and minimum speed at aphelion.",
    formula: {
      latex: "q = a(1 - e) \\quad \\text{and} \\quad Q = a(1 + e)",
      explanation: "Where a is the semi-major axis and e is the orbital eccentricity (0 <= e < 1).",
    },
    realWorldExample: "Earth reaches perihelion around January 3 (~147.1 million km / 0.983 AU) and aphelion around July 4 (~152.1 million km / 1.017 AU). Halley's Comet has a perihelion of 0.586 AU and an aphelion of 35.1 AU.",
    astronomicalRelevance: "Crucial for solar radiation flux modeling, climate cycle calculations (Milankovitch cycles), and planetary close-approach ephemeris forecasting.",
    difficulty: "Fundamental",
    tags: ["Keplerian Orbits", "Orbital Mechanics", "Eccentricity"],
    relatedTermIds: ["keplers-laws", "orbital-eccentricity", "escape-velocity"],
  },
  {
    id: "lagrange-points",
    slug: "lagrange-points",
    term: "Lagrange Points (L1 – L5)",
    category: "astrophysics",
    iauStandardNotation: "L₁, L₂, L₃, L₄, L₅",
    shortDefinition: "Five equilibrium positions in a two-body orbital system where the gravitational pull of two large masses equals the centripetal force required to orbit with them.",
    fullExplanation: "Formulated by Italian-French mathematician Joseph-Louis Lagrange in 1772, these five points allow a small third body (such as a space telescope or asteroid) to maintain a stationary position relative to the two primary orbital bodies. Points L1, L2, and L3 lie along the line connecting the two primaries and are dynamically unstable (requiring active station-keeping). Points L4 and L5 form equilateral triangles with the primaries and are dynamically stable, hosting natural 'Trojan' asteroid swarms.",
    formula: {
      latex: "r_{L1, L2} \\approx R \\left( \\frac{M_2}{3 M_1} \\right)^{1/3}",
      explanation: "Approximate distance of Sun-Earth L1 and L2 points from Earth (~1.5 million km), where R is 1 AU.",
    },
    realWorldExample: "The James Webb Space Telescope (JWST) and Gaia operate at Sun-Earth L2 for an unobstructed deep-space view and cold thermal environment. The SOHO solar observatory orbits Sun-Earth L1.",
    astronomicalRelevance: "Prime real estate for deep-space astronomy platforms, space weather early warning observatories, and Trojan asteroid science.",
    difficulty: "Intermediate",
    tags: ["Orbital Mechanics", "JWST", "Gravitation", "Spaceflight"],
    relatedTermIds: ["keplers-laws", "hohmann-transfer", "delta-v"],
  },
  {
    id: "escape-velocity",
    slug: "escape-velocity",
    term: "Escape Velocity",
    category: "astrophysics",
    iauStandardNotation: "v_e or v_esc",
    shortDefinition: "The minimum initial ballistic speed required for a non-propelled object to overcome the gravitational field of a celestial body without further propulsion.",
    fullExplanation: "Escape velocity is derived from the principle of conservation of mechanical energy, where an object's kinetic energy equals the gravitational potential energy needed to travel to an infinite distance. It depends solely on the mass and radius of the attracting body, independent of the mass of the escaping projectile. If an object is compressed such that its escape velocity equals the speed of light c, it forms an event horizon (Schwarzschild radius).",
    formula: {
      latex: "v_e = \\sqrt{\\frac{2 G M}{r}}",
      explanation: "Where G is the gravitational constant (6.67430 x 10^-11 m^3/kg/s^2), M is the body's mass, and r is the radius from the body's center of mass.",
    },
    realWorldExample: "Earth's surface escape velocity is ~11.186 km/s (40,270 km/h). The Moon's escape velocity is ~2.38 km/s, Mars is ~5.03 km/s, and the Sun's surface escape velocity is ~617.5 km/s.",
    astronomicalRelevance: "Governs atmospheric retention (lighter gases escape low-gravity worlds like the Moon), rocket propulsion requirements, and black hole formation criteria.",
    difficulty: "Fundamental",
    tags: ["Gravitation", "Rocketry", "Black Holes", "Orbital Mechanics"],
    relatedTermIds: ["event-horizon", "delta-v", "hohmann-transfer"],
  },
  {
    id: "keplers-laws",
    slug: "keplers-laws",
    term: "Kepler's Laws of Planetary Motion",
    category: "astrophysics",
    iauStandardNotation: "1st, 2nd, 3rd Laws",
    shortDefinition: "Three foundational mathematical laws formulated by Johannes Kepler describing the orbital motion of planets around the Sun.",
    fullExplanation: "1. Law of Ellipses: The orbit of a planet is an ellipse with the Sun at one of the two foci.\n2. Law of Equal Areas: A line segment joining a planet and the Sun sweeps out equal areas during equal intervals of time (orbital speed increases near perihelion).\n3. Law of Harmonies: The square of the orbital period (P) of a planet is directly proportional to the cube of the semi-major axis (a) of its orbit.",
    formula: {
      latex: "\\frac{P^2}{a^3} = \\frac{4\\pi^2}{G(M + m)} \\approx 1 \\quad (\\text{for } P \\text{ in years, } a \\text{ in AU, } M = M_\\odot)",
      explanation: "Newtonian generalization of Kepler's Third Law including total gravitational mass.",
    },
    realWorldExample: "Jupiter is 5.2 AU from the Sun: 5.2^3 = 140.6, and sqrt(140.6) = 11.86 Earth years, which precisely matches Jupiter's observed orbital period.",
    astronomicalRelevance: "Forms the mathematical backbone of all solar system orbital mechanics, satellite orbits, and exoplanetary detection via radial velocity and transit timing.",
    difficulty: "Fundamental",
    tags: ["Celestial Mechanics", "Historical Physics", "Planetary Motion"],
    relatedTermIds: ["perihelion-aphelion", "astronomical-unit", "orbital-eccentricity"],
  },
  {
    id: "roche-limit",
    slug: "roche-limit",
    term: "Roche Limit",
    category: "astrophysics",
    iauStandardNotation: "d_R",
    shortDefinition: "The critical orbital distance within which a celestial body held together only by self-gravity will disintegrate due to tidal forces exerted by a larger primary body.",
    fullExplanation: "Named after French astronomer Edouard Roche in 1848, the Roche limit defines the zone where tidal differential gravitational forces exceed the gravitational cohesion holding a satellite together. Inside this boundary, natural moons cannot coalesce from orbital debris, and approaching comets or asteroids are torn into fragmented streams. The spectacular ring systems of Saturn, Jupiter, Uranus, and Neptune lie primarily within their respective fluid/rigid Roche limits.",
    formula: {
      latex: "d_R \\approx 2.44 \\cdot R_M \\left( \\frac{\\rho_M}{\\rho_m} \\right)^{1/3} \\quad (\\text{Fluid Satellite})",
      explanation: "Where R_M is the primary's radius, and rho_M / rho_m are the densities of the primary and satellite respectively.",
    },
    realWorldExample: "Comet Shoemaker-Levy 9 passed within Jupiter's Roche limit in 1992, ripping the icy body into 21 distinct fragments that subsequently bombarded Jupiter in July 1994.",
    astronomicalRelevance: "Explains the genesis and maintenance of planetary rings, tidal disruption events (TDEs) around supermassive black holes, and accretion disk physics.",
    difficulty: "Advanced",
    tags: ["Tidal Forces", "Planetary Rings", "Black Holes", "Comets"],
    relatedTermIds: ["tidal-locking", "lagrange-points", "escape-velocity"],
  },

  // ── 2. PLANETARY DEFENSE & NEAR-EARTH OBJECTS (NEOs) ───────────────────────
  {
    id: "torino-scale",
    slug: "torino-scale",
    term: "Torino Impact Hazard Scale",
    category: "planetary-defense",
    iauStandardNotation: "Torino 0 – 10",
    shortDefinition: "A standardized 0-to-10 integer scale communicating the public risk of potential Earth-asteroid impact events within the next 100 years.",
    fullExplanation: "Adopted by the IAU in 1999 in Turin (Torino), Italy, this scale combines collision probability and kinetic impact energy (measured in Megatons of TNT) into an intuitive, color-coded index:\n- White (0): No hazard (certain miss or harmless burnup).\n- Green (1): Normal (routine discovery passing near Earth).\n- Yellow (2-4): Meriting attention by astronomers (diligent tracking required).\n- Orange (5-7): Threatening (critical close encounter causing local/regional devastation).\n- Red (8-10): Certain collisions (ranging from localized destruction to global civilization collapse at 10).",
    formula: {
      latex: "\\text{Torino Level} = f(P_{\\text{impact}}, E_{\\text{kinetic}})",
      explanation: "Function of collision probability P_impact and kinetic energy E_kinetic in Megatons of TNT.",
    },
    realWorldExample: "Asteroid 99942 Apophis briefly reached Torino Scale Level 4 in December 2004, causing international alarm until radar astrometry refined its orbit to Torino 0.",
    astronomicalRelevance: "Global communication bridge between planetary defense astrophysicists, NASA/ESA civil defense agencies, and the public.",
    difficulty: "Fundamental",
    tags: ["Planetary Defense", "Asteroids", "Risk Assessment", "NASA JPL"],
    relatedTermIds: ["palermo-scale", "pha", "kinetic-impactor", "yarkovsky-effect"],
  },
  {
    id: "palermo-scale",
    slug: "palermo-scale",
    term: "Palermo Technical Impact Hazard Scale",
    category: "planetary-defense",
    iauStandardNotation: "PS",
    shortDefinition: "A logarithmic technical scale used by asteroid dynamicists to quantify and prioritize the impact risk of Near-Earth Objects.",
    fullExplanation: "Unlike the public-oriented Torino Scale, the Palermo Scale is a continuous logarithmic value comparing the detected impact risk of an NEO against the historical 'background risk' posed by random cosmic impacts of equal or greater energy over the time until the potential encounter. A value of PS = 0 indicates a risk equal to the background hazard; PS = +2 represents a threat 100 times greater than the background risk.",
    formula: {
      latex: "PS = \\log_{10} \\left( \\frac{P_i}{f_B \\times \\Delta t} \\right) \\quad \\text{where } f_B = 0.03 \\cdot E^{-4/5}",
      explanation: "P_i is impact probability, Delta t is time to impact in years, and f_B is the annual background impact frequency for energy E in MT.",
    },
    realWorldExample: "Asteroid (29075) 1950 DA is one of the highest historically rated objects on the Palermo Scale (peaking at PS = +0.17 for a potential 2880 encounter).",
    astronomicalRelevance: "Used by NASA JPL Sentry and ESA NEODyS automated impact monitoring supercomputers for automated threat triage.",
    difficulty: "Advanced",
    tags: ["Planetary Defense", "Probability", "Algorithms", "NASA Sentry"],
    relatedTermIds: ["torino-scale", "pha", "kinetic-impactor"],
  },
  {
    id: "pha",
    slug: "pha",
    term: "Potentially Hazardous Asteroid (PHA)",
    category: "planetary-defense",
    iauStandardNotation: "PHA",
    shortDefinition: "A Near-Earth Asteroid with an orbit passing within 0.05 AU (19.5 Lunar Distances) of Earth and an absolute magnitude H <= 22.0 (diameter > 140m).",
    fullExplanation: "Potentially Hazardous Asteroids (PHAs) are a high-priority subset of Near-Earth Objects (NEOs). To qualify as a PHA under NASA/IAU guidelines, an asteroid must have an Earth Minimum Orbit Intersection Distance (MOID) of 0.05 AU (~7.48 million km) or less and be sufficiently large to cause significant regional devastation upon impact. An asteroid of 140 meters in diameter would release over 100 Megatons of TNT energy upon atmospheric impact.",
    formula: {
      latex: "\\text{MOID}_{\\oplus} \\le 0.05\\text{ AU} \\quad \\land \\quad H \\le 22.0 \\quad (D \\gtrsim 140\\text{ meters})",
      explanation: "Where MOID is Minimum Orbit Intersection Distance and H is absolute visual magnitude.",
    },
    realWorldExample: "Asteroids 99942 Apophis (370m) and 101955 Bennu (490m) are classified as PHAs, monitored continuously by NASA's Center for Near Earth Object Studies (CNEOS).",
    astronomicalRelevance: "Primary targets for optical survey telescopes (Pan-STARRS, Vera C. Rubin LSST, NEO Surveyor) and planetary defense deflection architectures.",
    difficulty: "Fundamental",
    tags: ["NEO", "Asteroids", "Planetary Defense", "NASA CNEOS"],
    relatedTermIds: ["torino-scale", "yarkovsky-effect", "kinetic-impactor"],
  },
  {
    id: "yarkovsky-effect",
    slug: "yarkovsky-effect",
    term: "Yarkovsky Effect",
    category: "planetary-defense",
    iauStandardNotation: "a_Y",
    shortDefinition: "A subtle non-gravitational thermal thrust force acting on small rotating asteroids caused by anisotropic thermal infrared emission.",
    fullExplanation: "Discovered by civil engineer Ivan Yarkovsky in 1901, this phenomenon occurs when an asteroid is heated by sunlight on its day side and subsequently radiates that thermal energy into space as it rotates to its afternoon/night side. Because thermal photons carry momentum, this delayed thermal re-radiation acts like a tiny, continuous propulsion engine, gradually altering the asteroid's semi-major axis over millions of years.",
    formula: {
      latex: "\\vec{F}_Y = -\\frac{2}{3 c} \\oint \\epsilon \\sigma T^4 \\hat{n} \\, dA",
      explanation: "Surface integral of thermal photon momentum recoil force across the asteroid's topography.",
    },
    realWorldExample: "Precise radar tracking of Asteroid 101955 Bennu revealed that the Yarkovsky effect shifts its orbit by approximately 284 meters per year, which was critical for calculating its 2182 impact probability.",
    astronomicalRelevance: "Indispensable parameter in high-precision astrometric orbital propagation for planetary defense trajectories over multi-decade baselines.",
    difficulty: "Advanced",
    tags: ["Thermal Physics", "Orbital Drift", "Asteroid Astrometry", "OSIRIS-REx"],
    relatedTermIds: ["pha", "palermo-scale", "keplers-laws"],
  },
  {
    id: "kinetic-impactor",
    slug: "kinetic-impactor",
    term: "Kinetic Impactor Deflection",
    category: "planetary-defense",
    iauStandardNotation: "Beta (β) Momentum Transfer",
    shortDefinition: "A planetary defense technique that alters an asteroid's orbital period by colliding a high-speed robotic spacecraft directly into its surface.",
    fullExplanation: "The kinetic impactor method is the most technologically mature asteroid deflection strategy. By slamming a spacecraft into a hazardous asteroid at velocities of several kilometers per second, momentum is transferred to the body. Crucially, the high-velocity ejecta blasted into space acts like a rocket thruster in reverse, multiplying the momentum transfer by a factor known as beta (beta > 1).",
    formula: {
      latex: "\\Delta \\vec{v} = \\beta \\frac{m_{\\text{craft}}}{M_{\\text{asteroid}}} \\vec{v}_{\\text{rel}}",
      explanation: "Where beta is the momentum enhancement factor from crater ejecta recoil, typically between 1.5 and 4.0.",
    },
    realWorldExample: "NASA's DART (Double Asteroid Redirection Test) mission successfully impacted Dimorphos on September 26, 2022, shortening its orbital period by 33 minutes and confirming a momentum multiplier beta = 3.6.",
    astronomicalRelevance: "Validated primary defense methodology for diverting hazardous asteroids with decade-scale early warning times.",
    difficulty: "Intermediate",
    tags: ["NASA DART", "Planetary Defense", "Impact Deflection", "Space Missions"],
    relatedTermIds: ["pha", "torino-scale", "delta-v"],
  },

  // ── 3. ASTROMETRY & OBSERVATIONAL ASTRONOMY ─────────────────────────────────
  {
    id: "right-ascension-declination",
    slug: "right-ascension-declination",
    term: "Right Ascension & Declination (RA / Dec)",
    category: "astrometry",
    iauStandardNotation: "α (RA), δ (Dec)",
    shortDefinition: "The fundamental equatorial celestial coordinate system mapping positions of stars and objects across the celestial sphere relative to Earth's equator.",
    fullExplanation: "Equatorial coordinates are the celestial equivalent of terrestrial longitude and latitude:\n- Right Ascension (RA / alpha): Measured eastward along the celestial equator from the Vernal Equinox (First Point of Aries) in hours, minutes, and seconds (0h to 24h, where 24h = 360 deg).\n- Declination (Dec / delta): Measured north (+) or south (-) from the celestial equator in degrees, arcminutes, and arcseconds (-90 deg to +90 deg).",
    formula: {
      latex: "\\text{RA } (\\alpha) \\in [0^h, 24^h) \\quad \\text{and} \\quad \\text{Dec } (\\delta) \\in [-90^\\circ, +90^\\circ]",
      explanation: "1 hour of RA = 15 degrees of sky rotation; 1 minute of RA = 15 arcminutes.",
    },
    realWorldExample: "Sirius (Alpha Canis Majoris), the brightest star in the night sky, is located at RA 06h 45m 09s, Dec -16 deg 42' 58''. The North Star (Polaris) is at RA 02h 31m, Dec +89 deg 15'.",
    astronomicalRelevance: "Universal standard for telescope pointing, star catalogs (Yale BSC5, Hipparcos, Gaia DR3), and orbital ephemerides.",
    difficulty: "Fundamental",
    tags: ["Celestial Sphere", "Coordinates", "Telescopes", "Star Catalogs"],
    relatedTermIds: ["altitude-azimuth", "sidereal-time", "epoch-j2000"],
  },
  {
    id: "altitude-azimuth",
    slug: "altitude-azimuth",
    term: "Altitude & Azimuth (Alt / Az)",
    category: "astrometry",
    iauStandardNotation: "a or h (Alt), A or Az (Azimuth)",
    shortDefinition: "The local horizontal coordinate system describing the exact pointing direction of an astronomical object relative to a specific ground observer's horizon.",
    fullExplanation: "Horizontal coordinates are topocentric (dependent on the observer's specific geographic latitude, longitude, and current local time):\n- Altitude (Alt / a): The angular height of an object measured vertically from the true horizon (0 deg) to the zenith directly overhead (+90 deg).\n- Azimuth (Az / A): The horizontal direction measured along the horizon eastward from True North (North = 0 deg, East = 90 deg, South = 180 deg, West = 270 deg).",
    formula: {
      latex: "\\sin(a) = \\sin(\\phi)\\sin(\\delta) + \\cos(\\phi)\\cos(\\delta)\\cos(H)",
      explanation: "Trigonometric conversion from Equatorial (Dec delta, Hour Angle H) to Altitude a for observer latitude phi.",
    },
    realWorldExample: "If the planet Saturn is reported at Alt 45 deg, Az 180 deg, an observer simply faces due South and looks halfway up between the horizon and the overhead zenith.",
    astronomicalRelevance: "Essential for telescope Alt-Az robotic tracking mounts, ground planetariums, and naked-eye sky observation.",
    difficulty: "Fundamental",
    tags: ["Planetarium", "Observing", "Horizon", "Telescopes"],
    relatedTermIds: ["right-ascension-declination", "sidereal-time", "epoch-j2000"],
  },
  {
    id: "sidereal-time",
    slug: "sidereal-time",
    term: "Sidereal Time (GMST / LST)",
    category: "astrometry",
    iauStandardNotation: "θ (GST), θ_L (LST)",
    shortDefinition: "A timekeeping system measured relative to the apparent rotation of the distant stars rather than the Sun (1 sidereal day is ~23h 56m 4s).",
    fullExplanation: "Because Earth orbits the Sun while rotating, it must rotate an extra ~0.986 degrees each day to realign with the Sun (creating the standard 24-hour solar day). A sidereal day measures the true 360-degree rotation of Earth relative to the Vernal Equinox and distant inertial celestial frame, which is approximately 3 minutes and 56 seconds shorter than a solar day. Local Sidereal Time (LST) precisely identifies which Right Ascension is crossing the observer's local meridian.",
    formula: {
      latex: "1\\text{ Sidereal Day} = 86,164.0905\\text{ seconds} \\approx 23^h 56^m 04.0905^s",
      explanation: "LST = GMST + (Observer Longitude in Hours).",
    },
    realWorldExample: "At LST = 18h 00m, any star with RA = 18h 00m (such as Vega at RA 18h 36m) will be positioned precisely at its highest point on the sky (culmination/transit).",
    astronomicalRelevance: "Synchronizes observatory domes, telescope tracking drives, and real-time planetarium engines.",
    difficulty: "Intermediate",
    tags: ["Timekeeping", "Earth Rotation", "Equinox", "Observatory"],
    relatedTermIds: ["right-ascension-declination", "altitude-azimuth", "epoch-j2000"],
  },
  {
    id: "epoch-j2000",
    slug: "epoch-j2000",
    term: "Epoch J2000.0",
    category: "astrometry",
    iauStandardNotation: "J2000.0",
    shortDefinition: "The current standard international reference epoch for celestial coordinates and orbital elements, fixed at January 1, 2000, 12:00 Terrestrial Time.",
    fullExplanation: "Due to the gravitational pull of the Sun and Moon on Earth's equatorial bulge, Earth's rotational axis wobbles in a 25,772-year cycle known as axial precession (precession of the equinoxes). Consequently, celestial coordinates (RA/Dec) continuously drift over time. To prevent ambiguity, the astronomical community establishes standardized epochs. Epoch J2000.0 corresponds precisely to Julian Date JD 2451545.0.",
    formula: {
      latex: "\\text{Julian Date} = 2451545.0 \\text{ TT} \\quad (\\text{2000-01-01 12:00:00.000})",
      explanation: "Precession rate drifts celestial coordinates by approximately 50.3 arcseconds per year.",
    },
    realWorldExample: "All modern star catalogs, including NASA NeoWs, ESA Gaia, and the Yale Bright Star Catalog, publish coordinates indexed to Epoch J2000.0 before applying proper motion corrections.",
    astronomicalRelevance: "The foundational reference frame for astronomical databases, planetary ephemerides, and satellite tracking algorithms.",
    difficulty: "Intermediate",
    tags: ["Astrodynamics", "Precession", "Reference Frame", "IAU Standard"],
    relatedTermIds: ["right-ascension-declination", "sidereal-time"],
  },
  {
    id: "apparent-absolute-magnitude",
    slug: "apparent-absolute-magnitude",
    term: "Apparent & Absolute Magnitude",
    category: "astrometry",
    iauStandardNotation: "m (Apparent), M (Absolute)",
    shortDefinition: "Logarithmic scales measuring how bright a celestial body appears from Earth (apparent) versus its intrinsic luminosity at a standard distance of 10 parsecs (absolute).",
    fullExplanation: "Originating with Greek astronomer Hipparchus and formalized by Norman Pogson in 1856, the astronomical magnitude scale is inverse logarithmic: brighter stars have smaller (or negative) magnitudes. A difference of 5 magnitudes corresponds to an exact brightness factor of 100 (a 1-magnitude difference equals a factor of 2.512).\n- Apparent Magnitude (m): Visual brightness observed from Earth.\n- Absolute Magnitude (M): Intrinsic brightness if the object were placed exactly 10 parsecs (32.6 ly) away.",
    formula: {
      latex: "m - M = 5 \\log_{10}(d) - 5 = 5 \\log_{10}\\left(\\frac{d}{10\\text{ pc}}\\right)",
      explanation: "Distance modulus equation linking apparent magnitude m, absolute magnitude M, and distance d in parsecs.",
    },
    realWorldExample: "The Sun's apparent magnitude is m = -26.74 (blindingly bright due to proximity), but its intrinsic absolute magnitude is a modest M = +4.83. Rigel has an apparent magnitude of m = +0.13, but an immense absolute magnitude of M = -7.84.",
    astronomicalRelevance: "Enables astrophysicists to determine stellar distances, classify stellar luminosities on the Hertzsprung-Russell diagram, and establish standard candles (Cepheid variables, Type Ia supernovae).",
    difficulty: "Intermediate",
    tags: ["Luminosity", "Photometry", "Distance Modulus", "Stars"],
    relatedTermIds: ["parsec", "hertzsprung-russell", "chandrasekhar-limit"],
  },

  // ── 4. ORBITAL TECHNOLOGY & SPACEFLIGHT ─────────────────────────────────────
  {
    id: "hohmann-transfer",
    slug: "hohmann-transfer",
    term: "Hohmann Transfer Orbit",
    category: "orbital-mechanics",
    iauStandardNotation: "Δv_total = Δv₁ + Δv₂",
    shortDefinition: "The most fuel-efficient two-impulse elliptical orbital maneuver used to transfer a spacecraft between two coplanar circular orbits around a central body.",
    fullExplanation: "Proposed by German engineer Walter Hohmann in 1925, this maneuver uses an elliptical transfer orbit whose periapsis is tangent to the inner orbit and apoapsis is tangent to the outer orbit. The transfer requires two discrete propulsive burns (delta-v):\n1. Prograde burn to enter the elliptical transfer orbit.\n2. Second prograde burn at apoapsis to circularize into the target destination orbit.",
    formula: {
      latex: "\\Delta v_1 = \\sqrt{\\frac{\\mu}{r_1}} \\left( \\sqrt{\\frac{2 r_2}{r_1 + r_2}} - 1 \\right), \\quad \\Delta v_2 = \\sqrt{\\frac{\\mu}{r_2}} \\left( 1 - \\sqrt{\\frac{2 r_1}{r_1 + r_2}} \\right)",
      explanation: "Where mu is standard gravitational parameter GM, r1 is initial orbit radius, and r2 is target orbit radius.",
    },
    realWorldExample: "Mars launch windows occur every ~26 months when Earth and Mars align to allow a ~9-month Hohmann transfer requiring minimal propellant.",
    astronomicalRelevance: "The foundational trajectory calculation for all interplanetary exploration missions (Mars rovers, Venus probes, lunar landers).",
    difficulty: "Intermediate",
    tags: ["Spaceflight", "Rocketry", "Interplanetary Trajectory", "Delta-V"],
    relatedTermIds: ["delta-v", "gravitational-slingshot", "escape-velocity"],
  },
  {
    id: "gravitational-slingshot",
    slug: "gravitational-slingshot",
    term: "Gravitational Slingshot (Gravity Assist)",
    category: "orbital-mechanics",
    iauStandardNotation: "Gravity Assist / Flyby",
    shortDefinition: "An orbital maneuver using the relative motion and gravitational field of a planet or moon to alter a spacecraft's speed and trajectory without consuming fuel.",
    fullExplanation: "During a hyperbolic gravity assist flyby, energy is conserved in the reference frame of the planet. However, in the heliocentric (Sun-centered) reference frame, the spacecraft 'steals' an imperceptible amount of the planet's orbital momentum, gaining a significant velocity boost (or deceleration, depending on the approach trajectory angle) and direction change.",
    formula: {
      latex: "v_{\\text{final, helio}} = \\vec{v}_{\\text{planet}} + \\vec{v}_{\\text{out, relative}} \\quad (\\Delta v_{\\text{max}} \\approx 2 v_{\\text{planet}})",
      explanation: "Maximum theoretical speed gain approaches twice the orbital velocity of the assist planet.",
    },
    realWorldExample: "Voyager 1 & 2 utilized gravity assists from Jupiter, Saturn, Uranus, and Neptune to achieve solar system escape velocity. NASA's Parker Solar Probe uses repeated Venus flybys to lower its perihelion near the Sun.",
    astronomicalRelevance: "Makes deep-space exploration to the outer solar system and interstellar space feasible within current chemical propulsion limits.",
    difficulty: "Intermediate",
    tags: ["Voyager", "Flyby", "Astrodynamics", "Interplanetary"],
    relatedTermIds: ["hohmann-transfer", "delta-v", "escape-velocity"],
  },
  {
    id: "sgp4-tle",
    slug: "sgp4-tle",
    term: "Two-Line Element Set (TLE) & SGP4",
    category: "orbital-mechanics",
    iauStandardNotation: "TLE / SGP4 Model",
    shortDefinition: "The global aerospace data format (TLE) and numerical propagator algorithm (SGP4) used to track and predict satellite orbital positions in Earth orbit.",
    fullExplanation: "A Two-Line Element Set (TLE) encodes the 6 classical Keplerian orbital elements along with atmospheric drag ballistic coefficients (B*) for a satellite at a specific epoch. The Simplified General Perturbations-4 (SGP4) mathematical propagator calculates real-time satellite positions by accounting for Earth's non-spherical gravitational oblateness (J2, J3, J4 zonal harmonics), atmospheric drag perturbations, and solar-lunar gravitational tides.",
    formula: {
      latex: "\\text{Position}(t), \\text{Velocity}(t) = \\text{SGP4}(\\text{TLE}, \\Delta t)",
      explanation: "TLE Line 1: Catalog number, epoch, drag term. Line 2: Inclination, RAAN, Eccentricity, Argument of Perigee, Mean Anomaly, Mean Motion.",
    },
    realWorldExample: "The International Space Station (ISS, NORAD ID: 25544) and the Tiangong Space Station have new TLEs published multiple times daily by Space-Track/NORAD to maintain sub-kilometer positional tracking.",
    astronomicalRelevance: "Core mathematical engine powering all satellite tracking stations, collision avoidance alerts (conjunction assessments), and planetarium satellite passes.",
    difficulty: "Advanced",
    tags: ["Satellites", "ISS", "NORAD", "Space Debris", "SGP4"],
    relatedTermIds: ["hohmann-transfer", "delta-v", "keplers-laws"],
  },
  {
    id: "delta-v",
    slug: "delta-v",
    term: "Delta-V (Δv) & Rocket Equation",
    category: "orbital-mechanics",
    iauStandardNotation: "Δv",
    shortDefinition: "The total change in velocity required to perform an orbital maneuver, serving as the fundamental 'currency' of spacecraft propulsion and mission planning.",
    fullExplanation: "Delta-v is a scalar impulse measure of the effort needed to change an orbit. Regardless of spacecraft mass, an orbital change from Low Earth Orbit (LEO) to a geostationary transfer orbit (GTO) requires a fixed amount of Delta-v (~2,440 m/s). Tsiolkovsky's Rocket Equation mathematically dictates the exponential propellant mass required to deliver a given delta-v based on engine specific impulse (I_sp).",
    formula: {
      latex: "\\Delta v = I_{\\text{sp}} \\cdot g_0 \\cdot \\ln\\left( \\frac{m_0}{m_f} \\right)",
      explanation: "Tsiolkovsky Rocket Equation: I_sp is specific impulse in seconds, g_0 is 9.80665 m/s^2, m_0 is wet initial mass, m_f is dry final mass.",
    },
    realWorldExample: "Reaching Low Earth Orbit from Earth's surface requires ~9,400 m/s of Delta-v (including atmospheric drag and gravity losses). A Moon landing and return requires ~15,000 m/s total Delta-v.",
    astronomicalRelevance: "Universal engineering constraint governing payload capacity, stage design, and deep-space mission viability.",
    difficulty: "Fundamental",
    tags: ["Rocketry", "Propulsion", "Tsiolkovsky", "Space Missions"],
    relatedTermIds: ["escape-velocity", "hohmann-transfer", "gravitational-slingshot"],
  },
  {
    id: "deep-space-network",
    slug: "deep-space-network",
    term: "Deep Space Network (DSN)",
    category: "orbital-mechanics",
    iauStandardNotation: "NASA DSN",
    shortDefinition: "An international array of giant parabolic radio antennas positioned ~120 degrees apart on Earth supporting interplanetary spacecraft communication and radar science.",
    fullExplanation: "Operated by NASA's Jet Propulsion Laboratory (JPL), the Deep Space Network consists of three premier ground communication complexes:\n1. Goldstone, California (Mojave Desert)\n2. Madrid, Spain (Robledo de Chavela)\n3. Canberra, Australia (Tidbinbilla)\nBecause the stations are separated by approximately 120 degrees of longitude, as Earth rotates, at least one facility maintains continuous line-of-sight communication with distant deep-space probes beyond the Moon.",
    formula: {
      latex: "P_{\\text{received}} \\propto \\frac{P_{\\text{trans}} G_{\\text{trans}} G_{\\text{rec}} \\lambda^2}{(4\\pi d)^2}",
      explanation: "Friis transmission equation demonstrating why deep-space signals attenuate with the inverse square of astronomical distance (d^2).",
    },
    realWorldExample: "DSN's 70-meter dish antennas communicate with Voyager 1 across a 45-hour round-trip radio signal delay, detecting signals weaker than a billionth of a billionth of a watt.",
    astronomicalRelevance: "The indispensable telemetry backbone for planetary exploration, asteroid radar imaging (Goldstone radar), and radio science.",
    difficulty: "Fundamental",
    tags: ["NASA JPL", "Radio Astronomy", "Deep Space Telemetry", "Voyager"],
    relatedTermIds: ["sgp4-tle", "delta-v"],
  },

  // ── 5. STELLAR ASTROPHYSICS & COSMOLOGY ─────────────────────────────────────
  {
    id: "hertzsprung-russell",
    slug: "hertzsprung-russell",
    term: "Hertzsprung-Russell (H-R) Diagram",
    category: "stellar-physics",
    iauStandardNotation: "H-R Diagram",
    shortDefinition: "A foundational scatter plot of stars showing the direct relationship between stellar absolute magnitude/luminosity versus stellar temperature/spectral type.",
    fullExplanation: "Independently developed by Ejnar Hertzsprung (1911) and Henry Norris Russell (1913), the H-R diagram is the master roadmap of stellar astrophysics. Stars are categorized into distinct evolutionary tracks:\n- Main Sequence: The prominent diagonal band where stars fuse hydrogen into helium (includes our Sun).\n- Red Giants & Supergiants: Luminous, cool stars in late evolutionary stages occupying the top right.\n- White Dwarfs: Hot, dense degenerate stellar remnants residing in the bottom left.",
    formula: {
      latex: "L = 4\\pi R^2 \\sigma T_{\\text{eff}}^4 \\quad \\implies \\quad \\log(L) = 2\\log(R) + 4\\log(T_{\\text{eff}}) + \\text{const}",
      explanation: "Stefan-Boltzmann luminosity relation linking stellar radius R, effective surface temperature T_eff, and total luminosity L.",
    },
    realWorldExample: "Our Sun is a G2V main-sequence star with T_eff ~5,778 K and L = 1 L_odot. Betelgeuse is a red supergiant with L ~100,000 L_odot, and Sirius B is a white dwarf with L ~0.056 L_odot.",
    astronomicalRelevance: "Essential tool for calculating star cluster ages, determining stellar evolutionary lifecycles, and estimating cosmic distances via main-sequence fitting.",
    difficulty: "Fundamental",
    tags: ["Stellar Evolution", "Luminosity", "Spectral Classification", "Stars"],
    relatedTermIds: ["chandrasekhar-limit", "apparent-absolute-magnitude", "event-horizon"],
  },
  {
    id: "chandrasekhar-limit",
    slug: "chandrasekhar-limit",
    term: "Chandrasekhar Limit",
    category: "stellar-physics",
    iauStandardNotation: "M_Ch ≈ 1.4 M_☉",
    shortDefinition: "The maximum theoretical mass of a stable white dwarf star (~1.44 Solar masses) above which electron degeneracy pressure cannot prevent gravitational collapse.",
    fullExplanation: "Calculated by Indian-American astrophysicist Subrahmanyan Chandrasekhar in 1930 at age 19 (for which he won the 1983 Nobel Prize in Physics). In a white dwarf, inward gravitational collapse is halted by quantum mechanical electron degeneracy pressure (Pauli Exclusion Principle). If a white dwarf accretes matter exceeding 1.44 Solar masses, relativistic electron speeds can no longer support the star, triggering a catastrophic Type Ia supernova explosion or collapse into a neutron star.",
    formula: {
      latex: "M_{\\text{Ch}} \\approx \\frac{\\omega_3^0}{4\\pi} \\left( \\frac{h c}{G} \\right)^{3/2} \\left( \\frac{1}{\\mu_e m_H} \\right)^2 \\approx 1.44 M_\\odot",
      explanation: "Derived from combining special relativity, quantum mechanics, and hydrostatic equilibrium.",
    },
    realWorldExample: "Type Ia supernovae (which occur when a white dwarf reaches M_Ch in a binary system) possess an extraordinarily uniform peak luminosity (M_V ~ -19.3), making them universal 'standard candles' that revealed the accelerating expansion of the universe.",
    astronomicalRelevance: "Defines the boundary between white dwarfs, neutron stars, and stellar-mass black holes, and anchors cosmic expansion rate measurements.",
    difficulty: "Advanced",
    tags: ["Quantum Astrophysics", "Supernovae", "White Dwarfs", "Nobel Prize"],
    relatedTermIds: ["hertzsprung-russell", "event-horizon", "dark-matter-energy"],
  },
  {
    id: "event-horizon",
    slug: "event-horizon",
    term: "Event Horizon & Schwarzschild Radius",
    category: "stellar-physics",
    iauStandardNotation: "r_s",
    shortDefinition: "The boundary surrounding a black hole beyond which the gravitational pull is so intense that nothing—not even photons of light—can escape.",
    fullExplanation: "Derived from Albert Einstein's General Theory of Relativity by Karl Schwarzschild in 1916. The event horizon represents a one-way causal boundary in spacetime. The radius of the event horizon for a non-rotating (Schwarzschild) black hole is directly proportional to its mass. Inside the event horizon, the escape velocity exceeds the speed of light c, and all matter inevitably collapses toward the central gravitational singularity.",
    formula: {
      latex: "r_s = \\frac{2 G M}{c^2}",
      explanation: "Schwarzschild radius formula: For Earth, r_s ≈ 9 mm; for the Sun, r_s ≈ 2.95 km; for Sagittarius A* (4.3 million M_☉), r_s ≈ 12.7 million km.",
    },
    realWorldExample: "The Event Horizon Telescope (EHT) collaboration captured the first direct silhouette images of the supermassive black hole event horizons in galaxy M87* (2019) and the Milky Way's Sagittarius A* (2022).",
    astronomicalRelevance: "The ultimate testing ground for general relativity, gravitational wave astrophysics (LIGO/Virgo), and quantum gravity paradoxes.",
    difficulty: "Intermediate",
    tags: ["Black Holes", "General Relativity", "Singularity", "EHT"],
    relatedTermIds: ["escape-velocity", "chandrasekhar-limit", "gravitational-waves"],
  },
  {
    id: "gravitational-waves",
    slug: "gravitational-waves",
    term: "Gravitational Waves",
    category: "stellar-physics",
    iauStandardNotation: "h (Strain Amplitude)",
    shortDefinition: "Ripples in the fabric of spacetime generated by accelerated massive celestial objects (such as colliding black holes or merging neutron stars).",
    fullExplanation: "Predicted by Albert Einstein in 1916 as a consequence of General Relativity, gravitational waves travel across the cosmos at the speed of light c. As they pass through matter, they cause a fractional distortion (strain h) in spatial distances, stretching spacetime along one perpendicular axis while compressing it along the other. Because gravity interacts extremely weakly with matter, gravitational waves travel across cosmological distances unimpeded by interstellar dust.",
    formula: {
      latex: "h = \\frac{\\Delta L}{L} \\sim 10^{-21} \\quad (\\text{LIGO detection sensitivity})",
      explanation: "Strain amplitude h represents a displacement Delta L less than 1/10,000th the diameter of a proton over a 4-kilometer laser interferometer arm.",
    },
    realWorldExample: "On September 14, 2015, the LIGO observatory achieved the historic first direct detection (GW150914) of gravitational waves from the merger of two black holes (36 M_odot and 29 M_odot) located 1.3 billion light-years away.",
    astronomicalRelevance: "Inaugurated the era of multi-messenger astronomy, allowing humanity to 'listen' to dark cosmic collisions invisible to traditional electromagnetic telescopes.",
    difficulty: "Advanced",
    tags: ["LIGO", "Spacetime", "Einstein", "Multi-Messenger Astronomy"],
    relatedTermIds: ["event-horizon", "chandrasekhar-limit"],
  },
  {
    id: "dark-matter-energy",
    slug: "dark-matter-energy",
    term: "Dark Matter & Dark Energy",
    category: "stellar-physics",
    iauStandardNotation: "Ω_m (Matter), Ω_Λ (Dark Energy)",
    shortDefinition: "The two invisible constituents dominating the cosmos: Dark Matter (27%) provides gravitational glue, while Dark Energy (68%) drives the accelerated expansion of the universe.",
    fullExplanation: "According to the standard Lambda-CDM cosmological model, ordinary baryonic matter (atoms making up all stars, planets, and humans) accounts for only ~5% of the total mass-energy budget of the universe:\n- Dark Matter (~26.8%): Non-luminous matter detected via its gravitational effects on galactic rotation curves (Vera Rubin) and gravitational lensing of galaxy clusters.\n- Dark Energy (~68.3%): A pervasive negative-pressure energy density (cosmological constant Lambda) driving the accelerating expansion of spacetime.",
    formula: {
      latex: "\\Omega_{\\text{total}} = \\Omega_{\\text{baryon}} (0.05) + \\Omega_{\\text{DM}} (0.27) + \\Omega_{\\Lambda} (0.68) \\approx 1.00 \\quad (\\text{Flat Universe})",
      explanation: "Critical density budget verified by the ESA Planck cosmic microwave background survey.",
    },
    realWorldExample: "The Bullet Cluster (1E 0657-56) provided direct empirical evidence of dark matter when gravitational lensing revealed the majority of the cluster's mass separated from the visible X-ray emitting colliding gas.",
    astronomicalRelevance: "The greatest unsolved mystery in modern physics, driving major international observatories (Euclid, Nancy Grace Roman Space Telescope, Vera Rubin LSST).",
    difficulty: "Intermediate",
    tags: ["Cosmology", "Lambda-CDM", "Planck", "Dark Universe"],
    relatedTermIds: ["redshift", "chandrasekhar-limit", "hertzsprung-russell"],
  },
  {
    id: "redshift",
    slug: "redshift",
    term: "Redshift (z) & Doppler Shift",
    category: "stellar-physics",
    iauStandardNotation: "z",
    shortDefinition: "The lengthening of electromagnetic wavelengths toward the red end of the spectrum caused by celestial objects moving away (Doppler) or the expansion of spacetime (Cosmological).",
    fullExplanation: "When light is emitted by an astronomical source moving away from an observer, its spectral absorption and emission lines shift toward longer, redder wavelengths. Cosmological redshift is not caused by objects moving through space, but rather by the metric expansion of spacetime stretching photons as they journey across the cosmos over billions of years.",
    formula: {
      latex: "z = \\frac{\\lambda_{\\text{obs}} - \\lambda_{\\text{emit}}}{\\lambda_{\\text{emit}}} = \\frac{a_0}{a(t)} - 1",
      explanation: "Where lambda_obs is observed wavelength, lambda_emit is laboratory rest wavelength, and a(t) is the cosmic scale factor.",
    },
    realWorldExample: "The James Webb Space Telescope detected galaxy JADES-GS-z14-0 at a record redshift of z = 14.32, witnessing light emitted just 290 million years after the Big Bang.",
    astronomicalRelevance: "Universal metric for measuring cosmic expansion rates (Hubble-Lemaitre Law v = H0 * d), lookback times, and mapping the 3D large-scale structure of the universe.",
    difficulty: "Intermediate",
    tags: ["Cosmology", "JWST", "Hubble Law", "Spectroscopy"],
    relatedTermIds: ["dark-matter-energy", "parsec", "light-year"],
  },

  // ── 6. PLANETARY SCIENCE & HABITABILITY ─────────────────────────────────────
  {
    id: "habitable-zone",
    slug: "habitable-zone",
    term: "Circumstellar Habitable Zone (Goldilocks Zone)",
    category: "planetary-science",
    iauStandardNotation: "HZ",
    shortDefinition: "The orbital region around a host star where planetary surface temperatures permit liquid water to exist under sufficient atmospheric pressure.",
    fullExplanation: "Because liquid water is considered the universal solvent essential for organic biochemistry, finding planets within the Habitable Zone is a primary criterion in exoplanet astrobiology. The boundaries of the Habitable Zone depend directly on the host star's luminosity and effective temperature: hot O/B/A stars have distant, wide habitable zones, while cool red M-dwarfs have compact, close-in habitable zones.",
    formula: {
      latex: "r_{\\text{in}} \\approx \\sqrt{\\frac{L_*}{1.1 L_\\odot}} \\text{ AU}, \\quad r_{\\text{out}} \\approx \\sqrt{\\frac{L_*}{0.53 L_\\odot}} \\text{ AU}",
      explanation: "Kopparapu empirical model estimating conservative inner (runaway greenhouse) and outer (maximum greenhouse) habitable zone boundaries.",
    },
    realWorldExample: "In our Solar System, Earth orbits securely inside the Habitable Zone (1.0 AU), while Venus lies just inside the inner boundary and Mars near the outer edge. Exoplanet Proxima Centauri b orbits in the habitable zone of our nearest stellar neighbor.",
    astronomicalRelevance: "Guides exoplanet atmosphere characterization missions (JWST, Habitable Worlds Observatory, Ariel) in the search for potential extraterrestrial biosignatures.",
    difficulty: "Fundamental",
    tags: ["Exoplanets", "Astrobiology", "Liquid Water", "JWST"],
    relatedTermIds: ["planetary-albedo", "tidal-locking", "astronomical-unit"],
  },
  {
    id: "magnetosphere",
    slug: "magnetosphere",
    term: "Planetary Magnetosphere & Van Allen Belts",
    category: "planetary-science",
    iauStandardNotation: "B-Field Topology",
    shortDefinition: "The protective magnetic cavity surrounding a planet generated by an internal geodynamo, deflecting harmful solar wind and cosmic radiation.",
    fullExplanation: "A planet's magnetosphere is created by the convective motion of electrically conductive molten metal inside its core (geodynamo mechanism). It acts as a planetary deflector shield against high-energy solar wind plasma. Where ionized particles are trapped by magnetic field lines, radiation belts (such as Earth's inner and outer Van Allen Belts) form, and energetic particles funneled toward the magnetic poles create auroras (Aurora Borealis & Australis).",
    formula: {
      latex: "R_{\\text{mp}} \\approx \\left( \\frac{B_0^2}{\\mu_0 \\rho v_{\\text{sw}}^2} \\right)^{1/6} R_p",
      explanation: "Stand-off distance of the subsolar magnetopause where planetary magnetic pressure balances dynamic solar wind ram pressure.",
    },
    realWorldExample: "Earth's active magnetosphere protected its atmosphere from being stripped away by the solar wind over 4.5 billion years, whereas Mars lost its global dynamo ~4 billion years ago, resulting in the loss of its thick atmosphere and liquid water.",
    astronomicalRelevance: "A decisive factor in evaluating long-term planetary habitability, atmospheric retention, and astronaut radiation shielding protocols.",
    difficulty: "Intermediate",
    tags: ["Geophysics", "Solar Wind", "Auroras", "Habitability"],
    relatedTermIds: ["habitable-zone", "karman-line", "planetary-albedo"],
  },
  {
    id: "tidal-locking",
    slug: "tidal-locking",
    term: "Tidal Locking (Synchronous Rotation)",
    category: "planetary-science",
    iauStandardNotation: "1:1 Spin-Orbit Resonance",
    shortDefinition: "The state where a celestial body's rotational period exactly matches its orbital period, causing the same hemisphere to perpetually face its primary partner.",
    fullExplanation: "Tidal locking occurs over astronomical timescales due to gravitational tidal friction. The primary body raises tidal bulges on the satellite; because the satellite rotates, these bulges are misaligned with the gravitational vector, exerting a torque that gradually slows the satellite's spin rate until its rotational period equals its orbital period (1:1 resonance).",
    formula: {
      latex: "t_{\\text{lock}} \\approx \\frac{\\omega_0 a^6 I Q}{3 G M_p^2 k_2 R_s^3}",
      explanation: "Tidal despinning timescale showing extreme sensitivity to orbital semi-major axis (proportional to a^6).",
    },
    realWorldExample: "Earth's Moon is tidally locked to Earth, which is why humanity only ever sees the near side from Earth's surface. Pluto and Charon are mutually tidally locked, each perpetually presenting the same face to the other.",
    astronomicalRelevance: "Most rocky exoplanets orbiting in the habitable zones of red dwarf stars (M-dwarfs, like TRAPPIST-1) are tidally locked, creating extreme permanent day/night temperature contrasts.",
    difficulty: "Intermediate",
    tags: ["Gravitation", "Moon", "Exoplanets", "Astrobiology"],
    relatedTermIds: ["roche-limit", "habitable-zone", "keplers-laws"],
  },
  {
    id: "planetary-albedo",
    slug: "planetary-albedo",
    term: "Planetary Albedo (Bond & Geometric)",
    category: "planetary-science",
    iauStandardNotation: "A_B (Bond), p (Geometric)",
    shortDefinition: "The fraction of incident solar electromagnetic radiation reflected back into space by a celestial body's surface and atmosphere (0 = blackbody absorption, 1 = total reflection).",
    fullExplanation: "Albedo directly dictates a planet's energy balance and equilibrium surface temperature:\n- Bond Albedo (A_B): The total fraction of incident solar energy reflected in all directions across all wavelengths.\n- Geometric Albedo (p): The reflectivity of a body observed at zero phase angle (full illumination) relative to an ideal Lambertian flat white disk.",
    formula: {
      latex: "T_{\\text{eq}} = \\left( \\frac{L_\\odot (1 - A_B)}{16\\pi \\sigma d^2} \\right)^{1/4}",
      explanation: "Planetary equilibrium temperature formula where T_eq depends inversely on distance d and directly on (1 - A_B).",
    },
    realWorldExample: "Venus has a high Bond albedo of A_B = 0.76 (its thick sulfuric clouds reflect 76% of sunlight). Earth has an albedo of A_B = 0.306, while the dark basaltic Moon reflects only A_B = 0.12.",
    astronomicalRelevance: "Essential for climate modeling, exoplanet phase curves, asteroid taxonomic classification (distinguishing dark C-type from bright S/M-types), and thermodynamic modeling.",
    difficulty: "Intermediate",
    tags: ["Atmosphere", "Climate", "Thermodynamics", "Asteroids"],
    relatedTermIds: ["habitable-zone", "apparent-absolute-magnitude"],
  },
  {
    id: "karman-line",
    slug: "karman-line",
    term: "Kármán Line",
    category: "planetary-science",
    iauStandardNotation: "Altitude 100 km",
    shortDefinition: "The internationally recognized boundary at an altitude of 100 km (62 miles) above Earth's mean sea level demarcating the edge of Earth's atmosphere and the beginning of outer space.",
    fullExplanation: "Formulated by Hungarian-American physicist and aeronautical engineer Theodore von Kármán. At this altitude, the Earth's atmosphere becomes so thin that an aerodynamic aircraft would have to travel faster than orbital velocity (~7.8 km/s) to generate sufficient aerodynamic lift to support its weight, rendering conventional aerodynamic flight physically impossible and orbital mechanics dominant.",
    formula: {
      latex: "L_{\\text{aero}} = \\frac{1}{2} \\rho(h) v^2 S C_L < m g \\quad \\implies \\quad v_{\\text{req}} > v_{\\text{orbital}} = \\sqrt{\\frac{GM}{R_E + h}}",
      explanation: "Aerodynamic lift L_aero falls below gravitational weight unless velocity exceeds circular orbital velocity.",
    },
    realWorldExample: "The Fédération Aéronautique Internationale (FAI) recognizes the 100 km Kármán Line as the official threshold for spaceflight and conferring astronaut status. NASA and the US Space Force use 80 km (50 miles).",
    astronomicalRelevance: "Establishes international space law jurisdictions (airspace sovereignty vs outer space treaty) and low-Earth satellite re-entry orbital decay boundaries.",
    difficulty: "Fundamental",
    tags: ["Space Boundary", "Aerodynamics", "Astronautics", "Atmosphere"],
    relatedTermIds: ["escape-velocity", "sgp4-tle", "delta-v"],
  },
];
